# Generated by Django 3.1.2 on 2021-11-15 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, unique=True)),
                ('school', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('mbti', models.CharField(blank=True, max_length=100)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('matching_check', models.BooleanField(default=False)),
                ('pair', models.CharField(blank=True, max_length=100)),
                ('balance_game', models.BooleanField(default=False)),
                ('stamp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Letterbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter_box', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.letterbox')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
