# Generated by Django 3.2.9 on 2021-11-19 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userPair', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('question', models.TextField()),
                ('answer', models.FileField(blank=True, upload_to='')),
                ('mission_check', models.BooleanField(default=False)),
                ('user_nickname', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_nickname', to='users.user')),
            ],
        ),
    ]
